export const GET_SESSION = 'GET_SESSION';
export const SET_SIGNUP_INPUT_FIRSTNAME = "SET_SIGNUP_INPUT_FIRSTNAME";
export const SET_SIGNUP_INPUT_LASTNAME = "SET_SIGNUP_INPUT_LASTNAME";
export const SET_SIGNUP_INPUT_EMAIL = "SET_SIGNUP_INPUT_EMAIL";
export const SET_SIGNUP_INPUT_PASSWORD = "SET_SIGNUP_INPUT_PASSWORD";
